REPARER LE MESSAGE D'ERREURE QUAND ON ENTRE DANS LA PAGE DE MEMBRE

RAMENER A L'ESPACE MEMBRE ARES AVOIR FINI L'INSCRIPTION 

METTRE UN BOUTON S ABONNER A LA NEWSLATTER DANS L'INSCRIPTION 

RAMENER A LA PAGE D'ACCEUIL SUR LA PAGE DE MEMBRE  

FAIRE FINIR LA PAGE CONTACTER 

METTRE UN LIEN A CONTACTER SUR LA PAGE MEMBRE 
